allowBuilds:
  sharp: true
  node-rdap@https://codeload.github.com/Appraise-Package/node-rdap/tar.gz/e1ec9452bfb6b601f3ff60cf065f7f2271ff5160: true

minimumReleaseAge: 1440
overrides:
  serialize-javascript@<=7.0.2: ^7.0.3
